### ISSUE TITLE
아이템5 any 타입 지양하기

### ISSUE THREAD

**Issue by Olivia1107** [Cozak92/Effective-TypeScript#4]
any 타입은 코드 리팩터링 때 버그를 감춥니다.

- 콜백이 있는 컴포넌트...?

**Comment by Cozak92** [comment]
콜백 = 함수가 끝난 뒤 실행되는 함수

자바스크립트에서 함수는 객체.
따라서 함수는 함수를 인자로 받고 다른 함수를 통해 반환될 수 있습니다. 인자로 대입되는 함수를 콜백함수라고 부릅니다


예시
```javascript
function whatYourName(name, callback) {
    console.log('name: ', name);
    callback();
}

function finishFunc() {
    console.log('finish function');
}

whatYourName('miniddo', finishFunc);

<output>
name: miniddo
finish function
```


컴포넌트는 그냥 대체가능한 모듈이라고 생각하시면 됩니다. 실생활로 예로 들자면 컴퓨터의 키보드나 마우스..?

**Comment by Cozak92** [comment]
콜백이 왜 쓰이는지에 대해서는 찾아보심 좋습니다!
